CREATE TABLE IF NOT EXISTS membership_groups (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    slug         VARCHAR(60) NOT NULL UNIQUE,
    title        VARCHAR(100) NOT NULL,
    subtitle     VARCHAR(150) DEFAULT NULL,
    note         TEXT DEFAULT NULL,
    sort_order   INT NOT NULL DEFAULT 0,
    active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
